version: "3.8"

services:
  yt-downloader:
    container_name: yt-downloader

    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "/app/.venv/bin/python3 -m uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "80:8000"


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - yt-downloader